#!/bin/bash

# Exit on non-zero return code (error) in any of the commands
set -e

# Change current directory to /tmp
cd /tmp/

# Remove old download.wapp
rm -f "SunBible.wapp"

# Download the wapp using wget (preinstalled)
echo "Download in progress..."
wget -O "SunBible.wapp" 'https://github.com/SunBible-dev/SunBible-Ubuntu-Web/releases/download/0.0.1/SunBible.wapp' &> /dev/null

echo ""
echo "Installing..."
# Install the wapp using wappinst (part of winst) and pass-run (authentication dialog of Ubuntu Web, preinstalled)
pass-run wappinst SunBible.wapp

# Remove download.wapp
rm -f SunBible.wapp